language: go
go:
- 1.x

notifications:
  email: false

env:
  GO111MODULE=on

jobs:
  include:
  - stage: unit tests
    script: 
    - go get ${gobuild_args} ./...
    - go test -v ./...
  - stage: deploy to staging
    script: make
    deploy:
      provider: heroku
      app: mysterious-atoll-78710
      api_key:
        secure: KChY4y75r0XMyf9EQPKSyd0NqLrEIoJ5E/gvV6znuUGkRQ/6hZf2Dw21d3b15yFg1LmZ5r8GmFC5RiTFWaeXRxhdtvPOM9QUtSWL00gEGmVs6Rk9UmnZxyAR51V2QZ66KPLdHiStn1KYzD9Gx750KxoxTWg9Ke1zCx/W6/UNMCGOE9uJzkALxN51tb3gfjbVilipmVoGW86227PInEbHrHOoj9QujMS8IE4lbEgjE2iA3aRAMntUtg+jxghgisD2QZOg9RYM3x79KSr/H+KhfCiHU107CQqb2+K/dOjyC2jEtj7fB93rgo4fVWiEa/axuUW+ot1ABubP+vmWAavibfynm2LKsVCalQaKQ/CfW4cdUnNuWFd30PHPHp9kj/S/2aZWjo/qEPjcaKUE6HxkqTxiJCdIATaSJ6zfsnUfmvLB0MCsK6rkaDW1ET2QN98DUv28GMav1eAFHpRXUf7s+PtqCDCjjHQNvQe0FKM2izLNHVlKWe7p6SkrXGuKEh39uMbzWjuiJUFes/w1o223CuKMmqnqbiw1q9/x0HX+kVUsmfwxWgSlYsaCQM4qvUstF4W0cm/oL951CKtxzdHdccVJiVtk9EmDrSiT+5eoMiZ8rU0dZGz3YJ8QR/ufaYmQGd3e1sHa1zFwavWA+zrLUu7kzlEdvDuQWRTeLoiGchg=
      on:
        repo: davidpgz/backend-coding-challenge
  - stage: test staging
    script: curl https://mysterious-atoll-78710.herokuapp.com
